### ISSUE TITLE
Slice - Network Service Composition 3.1.2

### ISSUE THREAD

**Issue by alemanyp** [sonata-nfv/tng-tests#115]
Slice that is comprised of 3 NS, 2 with 1 VNFs and 1 with 1 CNF, linked among them

**Task list:**
- [x]  Create SP folder
- [ ]  Create README
- [ ]  Create .robot
- [ ]  Create Jenkins job

**Comment by alemanyp** [comment]
- [ ]  Create SP folder
- [ ]  Create README
- [ ]  Create .robot
- [ ]  Create Jenkins job
